# Generated by Django 3.2.9 on 2021-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.CharField(choices=[('KD', 'KID'), ('AD', 'ADULTS')], default='KD', max_length=2),
        ),
    ]
