# Generated by Django 3.2.9 on 2021-11-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_alter_product_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
