# Generated by Django 3.2.9 on 2021-11-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_rename_catagory_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('KD', 'KIDS'), ('AD', 'ADULTS')], default='KD', max_length=2),
        ),
    ]
